#!/bin/bash



#update everything
apt-get -y remove --purge -y apache2* apache* php* mysql* ubuntu-release-upgrader-core landscape-common
apt-get update
apt-get install software-properties-common python-software-properties -y
sudo locale-gen en_US.UTF-8
export LANG=en_US.UTF-8
apt-add-repository ppa:ondrej/php -y
apt-get -y install fail2ban
apt-get update

#apt-get install apache2 php5.6 php5.6-cli libapache2-mod-php5.6 php5.6-gd php5.6-mysql php5.6-mcrypt php5.6-curl unzip php5.6-sqlite nano wget -y
apt-get -y install apache2 zip sudo htop php5.6-fpm php5.6-curl php5.6-gd php5.6-imap php5.6-mcrypt php5.6-readline php5.6-mysql php5.6-cli php5.6-common php5.6-curl php5.6-mbstring php5.6-bcmath php5.6-recode php5.6-mysql php5.6-opcache php-memcached php-imagick php-xdebug php-msgpack php5.6-zip php5.6-xml php5.6-soap php-memcache 


echo "<IfModule mod_dir.c>
    DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm
</IfModule>" > /etc/apache2/mods-enabled/dir.conf

service apache2 restart

echo "<VirtualHost *:80>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	#ServerName www.example.com

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html
	 <Directory /var/www/html/>
        AllowOverride All
    </Directory>

	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
" > /etc/apache2/sites-available/000-default.conf


a2enmod rewrite

service apache2 restart

cd /var/www/html

chown -R :www-data *

sudo php5enmod mcrypt
sudo service apache2 restart



