#!/bin/bash
wget http://www.rfxn.com/downloads/maldetect-current.tar.gz
tar -xvf maldetect-current.tar.gz
cd maldetect-*
./install.sh
maldet -u



apt-get install clamav clamav-daemon clamav-freshclam -y
/etc/init.d/clamav-daemon start

yum install clamav clamav-devel -y
freshclam

wget https://raw.githubusercontent.com/arsanto/ubuntu-blog-install/master/conf.maldet -O /usr/local/maldetect/conf.maldet
